"""review_items

Revision ID: 8aeb3071352e
Revises: 0c26454efe59
Create Date: 2026-05-03 19:34:26.158606

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8aeb3071352e"
down_revision: str | Sequence[str] | None = "0c26454efe59"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "review_items",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("risk_level", sa.String(), nullable=False),
        sa.Column("customer_tier", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("assigned_reviewer", sa.String(), nullable=True),
        sa.Column("notes_count", sa.Integer(), nullable=False),
        sa.Column("summary", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["status"],
            ["states.name"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("review_items")
    # ### end Alembic commands ###
